version: '3.9'
services:
  quiz-mvc:
    image: YOUR_USERNAME/quiz-mvc:0.0.1.RELEASE
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - quiz-db
    networks:
      - quiz-network

  # The value of 'DB_HOST' we reference in the MVC Dockerfile  
  quiz-db:
    image: YOUR_USERNAME/quiz-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - quiz-network
      
networks:
  quiz-network: